export const actionTypes = {
  GET_CONTACTS_SUCCESS: "GET_CONTACTS_SUCCESS",
  GET_CONTACTS_PENDING: "GET_CONTACTS_PENDING",
  GET_CONTACTS_FAILED: "GET_CONTACTS_FAILED",
  UPDATE_PAGE_NUMBER: "UPDATE_PAGE_NUMBER",
  UPDATE_PERSON_DETAIL: "UPDATE_PERSON_DETAIL",
  TOGGLE_DARK_MODE: "TOGGLE_DARK_MODE",
};
